"""made sites unique by url

Revision ID: c962db71c745
Revises: 119d2e41168c
Create Date: 2024-08-14 22:38:43.252835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c962db71c745'
down_revision: Union[str, None] = '119d2e41168c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sites', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='unique')
    # ### end Alembic commands ###
